# Generated by Django 4.0.3 on 2022-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=200)),
                ('cStudentId', models.CharField(max_length=100)),
                ('cDepartment', models.TextField(max_length=200)),
            ],
        ),
    ]
