# Generated by Django 4.0.3 on 2022-03-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeOcampo_WebPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinformations',
            name='cName',
            field=models.TextField(max_length=200),
        ),
    ]
